---
name: Ticket
about: Create a new ticket
labels: needs-triage
---

## Type

- [ ] Feature
- [ ] Bug
- [ ] Enhancement

## Description

<!-- Describe the current situation and what needs to be done -->

## Acceptance Criteria

- [ ] <!-- Add criteria -->

## Technical Info

- Area: [Frontend/Backend]
- Priority: [High/Medium/Low]
